### ISSUE TITLE
neovim-qt auto-quit

### ISSUE THREAD

**Issue by kdurant** [bfredl/nvim-lspmirror#1]
System: win10
neovim-qt will auto quit when open a python file。

I only add below in vimrc
```
call lsp#server#add('python', 'pyls')
```

**Comment by bfredl** [comment]
What is the nvim version? it is good to know.
Could you run `nvim.exe` in a console? then we might see an error message if nvim crashes.

**Comment by kdurant** [comment]
nvim version: v0.3.2-851

Run nvim.exe in a console is normal, But this plugin is not work

**Comment by bfredl** [comment]
probably this is the same issue as https://github.com/autozimu/LanguageClient-neovim/issues/661#issuecomment-443483520
